version: '2' 
networks:
  logicalprogression:
    driver: bridge

services:
  logicalprogression:
    build:
      context: ./
    container_name: logicalprogression 
    image: logicalprogression
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "5000:5000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      logicalprogression:
        aliases:
          - flask.logicalprogression
    volumes:
      - ./config:/config
    depends_on:
      - logicalDB

  logicalDB:
    image: mariadb:10.2
    user: "${UID}:${GID}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MYSQL_ROOT_PASSWORD: changeMe 
      MYSQL_DATABASE: logicalprogression
      PUID: ${UID}
      PGID: ${UID}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      logicalprogression:
        aliases:
          - db.logicalprogression

  logicalphpmyadmin:
    image: phpmyadmin/phpmyadmin 
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db.logicalprogression
    networks:
      logicalprogression:
        aliases:
          - admin.logicalprogression
    depends_on:
      - logicalDB

  logicalgrafana:
    image: grafana/grafana 
    volumes:
      - ./config/grafana:/etc/grafana
      - ./data/grafana:/var/lib/grafana
      - ./log/grafana:/var/log/grafana
      - /etc/localtime:/etc/localtime:ro
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "3001:3000"
    networks:
      logicalprogression:
        aliases:
          - grafana.logicalprogression
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=changeMe
    depends_on:
      - logicalDB
