version: '2' 
services:
  logicalprogression:
    build:
      context: .
    container_name: logicalprogression 
    image: logicalprogression
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "5000:5000"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
