{
 "title": "Climbing Overview",
 "time": { "from": "now/y", "to": "now/y" },
 "panels": [
  {
   "title": "Average Grade by Hold Type",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.grade) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) and boulder.sent = 1\ngroup by boulder.holdType"
    },
    {
     "rawSql": "select \navg(boulder.grade) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date))\ngroup by boulder.holdType\n"
    }
   ]
  },
  {
   "title": "Average Grade by Steepness",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.grade) as \"Grade Sent\",\nCONVERT(boulder.steepness,char) as \"steepness\", \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) and boulder.sent = 1\ngroup by boulder.steepness"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.grade) as \"Grade Sent\",\nCONVERT(boulder.steepness,char) as \"steepness\", \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) \ngroup by boulder.steepness"
    }
   ]
  },
  {
   "title": "Max Grade by Hold Type",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \nmax(boulder.grade) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) and boulder.sent = 1\ngroup by boulder.holdType"
    },
    {
     "rawSql": "select \nmax(boulder.grade) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date))\ngroup by boulder.holdType\n"
    }
   ]
  },
  {
   "title": "Average tries by Hold Type",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.tries) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) and boulder.sent = 1\ngroup by boulder.holdType"
    },
    {
     "rawSql": "select \navg(boulder.tries) as \"Grade Sent\",\nholdTypes.longEN, \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \ninner join holdTypes on boulder.holdType=holdTypes.short  \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date))\ngroup by boulder.holdType\n"
    }
   ]
  },
  {
   "title": "Average Tries by Steepness",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.tries) as \"tries Sent\",\nCONVERT(boulder.steepness,char) as \"steepness\", \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) and boulder.sent = 1\ngroup by boulder.steepness"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \navg(boulder.tries) as \"tries Sent\",\nCONVERT(boulder.steepness,char) as \"steepness\", \ndate as time_sec\nfrom sessions \ninner join boulder on sessions.ID = boulder.sessionID \nwhere boulder.warmUp!=1 and boulder.comment!=\"4x4\" and $__timeFilter(FROM_UNIXTIME(sessions.date)) \ngroup by boulder.steepness"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  date as time_sec,\n  SUM(boulder.grade * boulder.tries) as \"Sum\"\nFROM sessions\nINNER JOIN boulder ON boulder.sessionID = sessions.ID\nWHERE $__timeFilter(FROM_UNIXTIME(date)) AND boulder.warmUp != 1\nGROUP BY date\nORDER BY date ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  date as time_sec,\n  (SUM(boulder.grade * boulder.tries)/sessions.climbDuration)*10 as \"Density\"\nFROM sessions\nINNER JOIN boulder ON boulder.sessionID = sessions.ID\nWHERE $__timeFilter(FROM_UNIXTIME(date)) AND boulder.warmUp != 1\nGROUP BY date\nORDER BY date ASC"
    },
    {
     "rawSql": "SELECT\n  date as time_sec,\n  AVG(boulder.grade) as \"Average Grade\"\nFROM sessions\nINNER JOIN boulder ON boulder.sessionID = sessions.ID\nWHERE $__timeFilter(FROM_UNIXTIME(date)) AND boulder.warmUp != 1\nGROUP BY date\nORDER BY date ASC\n"
    },
    {
     "rawSql": "SELECT\n  date as time_sec,\n  AVG(boulder.grade) as \"Average Grade Sent\"\nFROM sessions\nINNER JOIN boulder ON boulder.sessionID = sessions.ID\nWHERE $__timeFilter(FROM_UNIXTIME(date)) AND boulder.warmUp != 1 AND boulder.Sent=1\nGROUP BY date\nORDER BY date ASC"
    }
   ]
  }
 ]
}